{% set name = "gfal2" %}
{% set version = "2.22.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.cern.ch/dmc/{{ name }}/-/archive/v{{ version }}/{{ name }}-v{{ version }}.tar.gz
  sha256: cabd0d353d801dd98df563e28b004984ae398ba77795c79f66ac90c287fcbd86
  patches:
    - 0001-Drop-CMakeCXX11Support.patch
    - 003-cryptopp.patch


build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - doxygen
    - pkg-config
    - sed
  host:
    - davix
    - glib
    - libssh2
    - libuuid
    - openldap
    - xrootd
    - zlib
    - cryptopp
    - json-c
    - pugixml
    - dcap
    - srm-ifce
    - gct
    - gtest
  run:
    - {{ pin_compatible('json-c', max_pin='x.x') }}

# Plugins requiring these dependencies are not currently built:
#   * lfc-devel
#   * dpm-devel
#   * libattr-devel

test:
  commands:
    - gfal2_version

about:
  home: http://dmc.web.cern.ch/projects/gfal-2/home
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: GFAL (Grid File Access Library) is a C library providing an abstraction layer of the grid storage system complexity.
  description: |
    GFAL (Grid File Access Library) is a C library providing an abstraction
    layer of the grid storage system complexity. The version 2 of GFAL tries to
    simplify at the maximum the file operations in a distributed environment.
    The complexity of the grid is hidden from the client side behind a simple
    common POSIX API. GFAL2 is able to manage all the common used file access
    protocols in a grid & cloud environment.
  doc_url: http://dmc.web.cern.ch/projects/gfal-2/documentation
  dev_url: https://gitlab.cern.ch/dmc/gfal2

extra:
  recipe-maintainers:
    - chrisburr
